<?php

namespace Database\Seeders;

use App\Models\Complaint;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ComplaintSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get petugas users for assignment
        $petugas = User::where('role', 'petugas')->get();
        $petugasIds = $petugas->pluck('id')->toArray();
        
        // If no petugas, create one for assignment
        if (empty($petugasIds)) {
            $petugasUser = User::firstOrCreate(
                ['email' => 'petugas@donoharjo.com'],
                [
                    'name' => 'Petugas Lapangan',
                    'password' => bcrypt('password'),
                    'role' => 'petugas',
                ]
            );
            $petugasIds = [$petugasUser->id];
        }

        $complaints = [
            [
                'name' => 'Budi Santoso',
                'phone' => '081234567890',
                'address' => 'Jl. Raya Donoharjo No. 45',
                'rt' => '01',
                'rw' => '03',
                'category' => 'infrastruktur',
                'title' => 'Jalan Berlubang di Jl. Raya Donoharjo',
                'description' => 'Ada lubang besar di jalan raya depan rumah saya, sangat berbahaya untuk kendaraan terutama saat malam hari. Sudah beberapa kali ada motor yang hampir jatuh.',
                'location_lat' => -7.7594,
                'location_lng' => 110.3714,
                'location_text' => 'Jl. Raya Donoharjo No. 45, RT 01/RW 03',
                'status' => 'in_progress',
                'assigned_to' => $petugasIds[0] ?? null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(12),
            ],
            [
                'name' => 'Siti Nurhaliza',
                'phone' => '081234567891',
                'address' => 'Jl. Merdeka No. 12',
                'rt' => '02',
                'rw' => '04',
                'category' => 'sampah',
                'title' => 'Sampah Menumpuk di TPS',
                'description' => 'Sampah di TPS sudah menumpuk dan tidak diangkut selama 3 hari. Menimbulkan bau tidak sedap dan mengundang lalat.',
                'location_lat' => -7.7600,
                'location_lng' => 110.3720,
                'location_text' => 'TPS Jl. Merdeka, RT 02/RW 04',
                'status' => 'todo',
                'assigned_to' => $petugasIds[0] ?? null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(2),
            ],
            [
                'name' => null,
                'phone' => '081234567892',
                'address' => null,
                'rt' => '03',
                'rw' => '05',
                'category' => 'air',
                'title' => 'Air PDAM Tidak Keluar',
                'description' => 'Sejak kemarin pagi air PDAM tidak keluar sama sekali. Sudah dicoba buka-tutup kran tapi tetap tidak ada air.',
                'location_lat' => -7.7610,
                'location_lng' => 110.3730,
                'location_text' => 'RT 03/RW 05, sekitar Masjid Al-Ikhlas',
                'status' => 'verification',
                'assigned_to' => null,
                'is_anonymous' => true,
                'sla_deadline' => now()->addDays(6),
            ],
            [
                'name' => 'Ahmad Fauzi',
                'phone' => '081234567893',
                'address' => 'Jl. Diponegoro No. 78',
                'rt' => '04',
                'rw' => '06',
                'category' => 'listrik',
                'title' => 'Lampu Jalan Mati',
                'description' => 'Lampu jalan di depan rumah sudah mati selama seminggu. Sangat gelap dan berbahaya untuk warga yang lewat malam hari.',
                'location_lat' => -7.7620,
                'location_lng' => 110.3740,
                'location_text' => 'Jl. Diponegoro No. 78, RT 04/RW 06',
                'status' => 'done',
                'assigned_to' => $petugasIds[0] ?? null,
                'is_anonymous' => false,
                'sla_deadline' => now()->subDays(2),
            ],
            [
                'name' => 'Rina Wati',
                'phone' => '081234567894',
                'address' => 'Jl. Gatot Subroto No. 23',
                'rt' => '05',
                'rw' => '07',
                'category' => 'keamanan',
                'title' => 'Aktivitas Mencurigakan di Malam Hari',
                'description' => 'Ada kendaraan mencurigakan yang sering lewat di malam hari sekitar pukul 23.00-01.00. Mohon ditingkatkan patroli keamanan.',
                'location_lat' => -7.7630,
                'location_lng' => 110.3750,
                'location_text' => 'Jl. Gatot Subroto No. 23, RT 05/RW 07',
                'status' => 'backlog',
                'assigned_to' => null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(5),
            ],
            [
                'name' => 'Dedi Kurniawan',
                'phone' => '081234567895',
                'address' => 'Jl. Sudirman No. 56',
                'rt' => '01',
                'rw' => '02',
                'category' => 'infrastruktur',
                'title' => 'Gorong-gorong Tersumbat',
                'description' => 'Gorong-gorong di depan rumah tersumbat sampah dan tanah. Setiap hujan air menggenang dan masuk ke halaman rumah.',
                'location_lat' => -7.7640,
                'location_lng' => 110.3760,
                'location_text' => 'Jl. Sudirman No. 56, RT 01/RW 02',
                'status' => 'in_progress',
                'assigned_to' => $petugasIds[0] ?? null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(10),
            ],
            [
                'name' => 'Maya Sari',
                'phone' => '081234567896',
                'address' => 'Jl. Ahmad Yani No. 34',
                'rt' => '06',
                'rw' => '08',
                'category' => 'sampah',
                'title' => 'Warga Membuang Sampah Sembarangan',
                'description' => 'Ada warga yang rutin membuang sampah di pinggir jalan, bukan di TPS. Sampah berserakan dan mengotori lingkungan.',
                'location_lat' => -7.7650,
                'location_lng' => 110.3770,
                'location_text' => 'Jl. Ahmad Yani No. 34, RT 06/RW 08',
                'status' => 'verification',
                'assigned_to' => null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(2),
            ],
            [
                'name' => 'Joko Widodo',
                'phone' => '081234567897',
                'address' => 'Jl. Kartini No. 67',
                'rt' => '07',
                'rw' => '09',
                'category' => 'sosial',
                'title' => 'Permohonan Bantuan untuk Warga Tidak Mampu',
                'description' => 'Ada keluarga di RT 07 yang sangat membutuhkan bantuan sembako. Kepala keluarga sakit dan tidak bisa bekerja.',
                'location_lat' => -7.7660,
                'location_lng' => 110.3780,
                'location_text' => 'Jl. Kartini No. 67, RT 07/RW 09',
                'status' => 'todo',
                'assigned_to' => null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(6),
            ],
            [
                'name' => 'Sri Handayani',
                'phone' => '081234567898',
                'address' => 'Jl. Pahlawan No. 89',
                'rt' => '08',
                'rw' => '10',
                'category' => 'kesehatan',
                'title' => 'Lingkungan Tidak Sehat di Sekitar Rumah',
                'description' => 'Ada genangan air kotor yang tidak mengalir di belakang rumah. Menimbulkan bau dan dikhawatirkan menjadi sarang nyamuk.',
                'location_lat' => -7.7670,
                'location_lng' => 110.3790,
                'location_text' => 'Jl. Pahlawan No. 89, RT 08/RW 10',
                'status' => 'in_progress',
                'assigned_to' => $petugasIds[0] ?? null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(4),
            ],
            [
                'name' => null,
                'phone' => '081234567899',
                'address' => null,
                'rt' => '09',
                'rw' => '11',
                'category' => 'listrik',
                'title' => 'Kabel Listrik Terkelupas',
                'description' => 'Ada kabel listrik yang terkelupas di tiang listrik. Sangat berbahaya terutama saat hujan. Mohon segera diperbaiki.',
                'location_lat' => -7.7680,
                'location_lng' => 110.3800,
                'location_text' => 'RT 09/RW 11, dekat SD Donoharjo',
                'status' => 'rejected',
                'assigned_to' => null,
                'is_anonymous' => true,
                'sla_deadline' => now()->subDays(1),
            ],
            [
                'name' => 'Bambang Sutrisno',
                'phone' => '081234567900',
                'address' => 'Jl. Soekarno-Hatta No. 11',
                'rt' => '10',
                'rw' => '12',
                'category' => 'infrastruktur',
                'title' => 'Jembatan Kecil Rusak',
                'description' => 'Jembatan kecil di jalan menuju sawah sudah retak dan tidak aman. Banyak warga yang lewat untuk ke sawah.',
                'location_lat' => -7.7690,
                'location_lng' => 110.3810,
                'location_text' => 'Jl. Soekarno-Hatta No. 11, RT 10/RW 12',
                'status' => 'todo',
                'assigned_to' => $petugasIds[0] ?? null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(11),
            ],
            [
                'name' => 'Indah Permata',
                'phone' => '081234567901',
                'address' => 'Jl. Hayam Wuruk No. 22',
                'rt' => '11',
                'rw' => '13',
                'category' => 'sampah',
                'title' => 'Bau Tidak Sedap dari Saluran Air',
                'description' => 'Saluran air di depan rumah mengeluarkan bau tidak sedap. Sepertinya ada yang tersumbat atau ada sampah yang membusuk.',
                'location_lat' => -7.7700,
                'location_lng' => 110.3820,
                'location_text' => 'Jl. Hayam Wuruk No. 22, RT 11/RW 13',
                'status' => 'verification',
                'assigned_to' => null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(2),
            ],
            [
                'name' => 'Eko Prasetyo',
                'phone' => '081234567902',
                'address' => 'Jl. Gajah Mada No. 33',
                'rt' => '12',
                'rw' => '14',
                'category' => 'air',
                'title' => 'Air Sumur Tercemar',
                'description' => 'Air sumur di rumah saya terlihat keruh dan berbau. Khawatir tercemar dari saluran pembuangan terdekat.',
                'location_lat' => -7.7710,
                'location_lng' => 110.3830,
                'location_text' => 'Jl. Gajah Mada No. 33, RT 12/RW 14',
                'status' => 'in_progress',
                'assigned_to' => $petugasIds[0] ?? null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(5),
            ],
            [
                'name' => 'Lina Marlina',
                'phone' => '081234567903',
                'address' => 'Jl. Imam Bonjol No. 44',
                'rt' => '13',
                'rw' => '15',
                'category' => 'pendidikan',
                'title' => 'Fasilitas Sekolah Perlu Perbaikan',
                'description' => 'Atap kelas di SD Donoharjo ada yang bocor. Saat hujan air masuk ke dalam kelas dan mengganggu proses belajar mengajar.',
                'location_lat' => -7.7720,
                'location_lng' => 110.3840,
                'location_text' => 'SD Donoharjo, Jl. Imam Bonjol, RT 13/RW 15',
                'status' => 'todo',
                'assigned_to' => null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(7),
            ],
            [
                'name' => 'Rudi Hartono',
                'phone' => '081234567904',
                'address' => 'Jl. Cut Nyak Dien No. 55',
                'rt' => '14',
                'rw' => '16',
                'category' => 'keamanan',
                'title' => 'Lampu Jalan di Gang Gelap',
                'description' => 'Gang kecil di RT 14 tidak ada lampu jalan. Sangat gelap dan berbahaya untuk warga yang pulang malam.',
                'location_lat' => -7.7730,
                'location_lng' => 110.3850,
                'location_text' => 'Jl. Cut Nyak Dien No. 55, RT 14/RW 16',
                'status' => 'done',
                'assigned_to' => $petugasIds[0] ?? null,
                'is_anonymous' => false,
                'sla_deadline' => now()->subDays(3),
            ],
            [
                'name' => 'Sari Dewi',
                'phone' => '081234567905',
                'address' => 'Jl. Teuku Umar No. 66',
                'rt' => '15',
                'rw' => '17',
                'category' => 'sosial',
                'title' => 'Permohonan Bantuan untuk Lansia',
                'description' => 'Ada nenek lansia di RT 15 yang hidup sendiri dan kesulitan untuk kebutuhan sehari-hari. Mohon bantuan untuk kunjungan rutin.',
                'location_lat' => -7.7740,
                'location_lng' => 110.3860,
                'location_text' => 'Jl. Teuku Umar No. 66, RT 15/RW 17',
                'status' => 'backlog',
                'assigned_to' => null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(6),
            ],
            [
                'name' => 'Agus Setiawan',
                'phone' => '081234567906',
                'address' => 'Jl. Ki Hajar Dewantara No. 77',
                'rt' => '16',
                'rw' => '18',
                'category' => 'infrastruktur',
                'title' => 'Trotoar Rusak dan Tidak Rata',
                'description' => 'Trotoar di depan pasar sudah rusak dan tidak rata. Banyak yang terangkat dan berbahaya untuk pejalan kaki, terutama lansia.',
                'location_lat' => -7.7750,
                'location_lng' => 110.3870,
                'location_text' => 'Jl. Ki Hajar Dewantara No. 77, RT 16/RW 18',
                'status' => 'in_progress',
                'assigned_to' => $petugasIds[0] ?? null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(13),
            ],
            [
                'name' => 'Nurul Hidayati',
                'phone' => '081234567907',
                'address' => 'Jl. R.A. Kartini No. 88',
                'rt' => '17',
                'rw' => '19',
                'category' => 'kesehatan',
                'title' => 'Puskesmas Perlu Perbaikan',
                'description' => 'AC di ruang tunggu Puskesmas tidak berfungsi. Pasien merasa tidak nyaman, terutama yang membawa anak kecil.',
                'location_lat' => -7.7760,
                'location_lng' => 110.3880,
                'location_text' => 'Puskesmas Donoharjo, Jl. R.A. Kartini, RT 17/RW 19',
                'status' => 'todo',
                'assigned_to' => null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(6),
            ],
            [
                'name' => 'Hendra Wijaya',
                'phone' => '081234567908',
                'address' => 'Jl. Sultan Agung No. 99',
                'rt' => '18',
                'rw' => '20',
                'category' => 'lainnya',
                'title' => 'Permohonan Pemasangan Papan Informasi',
                'description' => 'Mohon dipasang papan informasi desa di lokasi strategis. Agar warga mudah mendapatkan informasi penting tentang desa.',
                'location_lat' => -7.7770,
                'location_lng' => 110.3890,
                'location_text' => 'Jl. Sultan Agung No. 99, RT 18/RW 20',
                'status' => 'verification',
                'assigned_to' => null,
                'is_anonymous' => false,
                'sla_deadline' => now()->addDays(6),
            ],
            [
                'name' => 'Dewi Sartika',
                'phone' => '081234567909',
                'address' => 'Jl. Jenderal Sudirman No. 100',
                'rt' => '19',
                'rw' => '21',
                'category' => 'sampah',
                'title' => 'Sampah Plastik Menumpuk di Sungai',
                'description' => 'Ada banyak sampah plastik yang menumpuk di sungai kecil. Mengganggu aliran air dan merusak ekosistem.',
                'location_lat' => -7.7780,
                'location_lng' => 110.3900,
                'location_text' => 'Jl. Jenderal Sudirman No. 100, RT 19/RW 21',
                'status' => 'done',
                'assigned_to' => $petugasIds[0] ?? null,
                'is_anonymous' => false,
                'sla_deadline' => now()->subDays(5),
            ],
        ];

        foreach ($complaints as $index => $complaintData) {
            // Generate unique tracking code
            do {
                $trackingCode = 'ADU-' . strtoupper(Str::random(6));
            } while (Complaint::where('tracking_code', $trackingCode)->exists());

            $complaintData['tracking_code'] = $trackingCode;
            
            // Set created_at to vary (some older, some recent)
            $daysAgo = rand(0, 30);
            $createdAt = now()->subDays($daysAgo);
            
            Complaint::create(array_merge($complaintData, [
                'created_at' => $createdAt,
                'updated_at' => $createdAt->addHours(rand(1, 48)),
            ]));
        }

        $this->command->info('Created 20 dummy complaints successfully!');
    }
}
